use sea_schema::sqlite::discovery::{DiscoveryResult, SchemaDiscovery};

fn main() -> DiscoveryResult<()> {
    let url = std::env::var("DATABASE_URL_SAKILA")
        .unwrap_or_else(|_| "sqlite://tests/sakila/sqlite/sakila.db".to_owned());

    let connection = sea_schema::rusqlite_types::connect_sqlite(&url).unwrap();

    let schema_discovery = SchemaDiscovery::new(connection);

    let schema = schema_discovery.discover()?;

    assert_eq!(
        format!("{schema:#?}"),
        r#"Schema {
    tables: [
        TableDef {
            name: "actor",
            foreign_keys: [],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "actor_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "first_name",
                    type: String(
                        N(
                            45,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "last_name",
                    type: String(
                        N(
                            45,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: CurrentTimestamp,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: true,
        },
        TableDef {
            name: "country",
            foreign_keys: [],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "country_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "country",
                    type: String(
                        N(
                            50,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "last_update",
                    type: Timestamp,
                    not_null: false,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "city",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "country",
                    from: [
                        "country_id",
                    ],
                    to: [
                        "country_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "city_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "city",
                    type: String(
                        N(
                            50,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "country_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "address",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "city",
                    from: [
                        "city_id",
                    ],
                    to: [
                        "city_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "address_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "address",
                    type: String(
                        N(
                            50,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "address2",
                    type: String(
                        N(
                            50,
                        ),
                    ),
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "district",
                    type: String(
                        N(
                            20,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 4,
                    name: "city_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 5,
                    name: "postal_code",
                    type: String(
                        N(
                            10,
                        ),
                    ),
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 6,
                    name: "phone",
                    type: String(
                        N(
                            20,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 7,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "language",
            foreign_keys: [],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "language_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "name",
                    type: Char(
                        Some(
                            20,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "category",
            foreign_keys: [],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "category_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "name",
                    type: String(
                        N(
                            25,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "customer",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "address",
                    from: [
                        "address_id",
                    ],
                    to: [
                        "address_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "store",
                    from: [
                        "store_id",
                    ],
                    to: [
                        "store_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "customer_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "store_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "first_name",
                    type: String(
                        N(
                            45,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "last_name",
                    type: String(
                        N(
                            45,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 4,
                    name: "email",
                    type: String(
                        N(
                            50,
                        ),
                    ),
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 5,
                    name: "address_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 6,
                    name: "active",
                    type: Char(
                        Some(
                            1,
                        ),
                    ),
                    not_null: true,
                    default_value: String(
                        "Y",
                    ),
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 7,
                    name: "create_date",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 8,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "film",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "language",
                    from: [
                        "original_language_id",
                    ],
                    to: [
                        "language_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "language",
                    from: [
                        "language_id",
                    ],
                    to: [
                        "language_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "film_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "title",
                    type: String(
                        N(
                            255,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "description",
                    type: Text,
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "release_year",
                    type: String(
                        N(
                            4,
                        ),
                    ),
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 4,
                    name: "language_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 5,
                    name: "original_language_id",
                    type: SmallInteger,
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 6,
                    name: "rental_duration",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Integer(
                        3,
                    ),
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 7,
                    name: "rental_rate",
                    type: Decimal(
                        Some(
                            (
                                4,
                                2,
                            ),
                        ),
                    ),
                    not_null: true,
                    default_value: Float(
                        4.99,
                    ),
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 8,
                    name: "length",
                    type: SmallInteger,
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 9,
                    name: "replacement_cost",
                    type: Decimal(
                        Some(
                            (
                                5,
                                2,
                            ),
                        ),
                    ),
                    not_null: true,
                    default_value: Float(
                        19.99,
                    ),
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 10,
                    name: "rating",
                    type: String(
                        N(
                            10,
                        ),
                    ),
                    not_null: false,
                    default_value: String(
                        "G",
                    ),
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 11,
                    name: "special_features",
                    type: String(
                        N(
                            100,
                        ),
                    ),
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 12,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "film_actor",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "film",
                    from: [
                        "film_id",
                    ],
                    to: [
                        "film_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "actor",
                    from: [
                        "actor_id",
                    ],
                    to: [
                        "actor_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "actor_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "film_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "film_category",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "category",
                    from: [
                        "category_id",
                    ],
                    to: [
                        "category_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "film",
                    from: [
                        "film_id",
                    ],
                    to: [
                        "film_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "film_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "category_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "film_text",
            foreign_keys: [],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "film_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "title",
                    type: String(
                        N(
                            255,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "description",
                    type: Text,
                    not_null: false,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "inventory",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "film",
                    from: [
                        "film_id",
                    ],
                    to: [
                        "film_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "store",
                    from: [
                        "store_id",
                    ],
                    to: [
                        "store_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "inventory_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "film_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "store_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "staff",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "address",
                    from: [
                        "address_id",
                    ],
                    to: [
                        "address_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "store",
                    from: [
                        "store_id",
                    ],
                    to: [
                        "store_id",
                    ],
                    on_update: Cascade,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "staff_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "first_name",
                    type: String(
                        N(
                            45,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "last_name",
                    type: String(
                        N(
                            45,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "address_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 4,
                    name: "picture",
                    type: Blob,
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 5,
                    name: "email",
                    type: String(
                        N(
                            50,
                        ),
                    ),
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 6,
                    name: "store_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 7,
                    name: "active",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Integer(
                        1,
                    ),
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 8,
                    name: "username",
                    type: String(
                        N(
                            16,
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 9,
                    name: "password",
                    type: String(
                        N(
                            40,
                        ),
                    ),
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 10,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "store",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "address",
                    from: [
                        "address_id",
                    ],
                    to: [
                        "address_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "staff",
                    from: [
                        "manager_staff_id",
                    ],
                    to: [
                        "staff_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "store_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "manager_staff_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "address_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "payment",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "staff",
                    from: [
                        "staff_id",
                    ],
                    to: [
                        "staff_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "customer",
                    from: [
                        "customer_id",
                    ],
                    to: [
                        "customer_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 2,
                    seq: 0,
                    table: "rental",
                    from: [
                        "rental_id",
                    ],
                    to: [
                        "rental_id",
                    ],
                    on_update: Cascade,
                    on_delete: SetNull,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "payment_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "customer_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "staff_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "rental_id",
                    type: BigInteger,
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 4,
                    name: "amount",
                    type: Decimal(
                        Some(
                            (
                                5,
                                2,
                            ),
                        ),
                    ),
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 5,
                    name: "payment_date",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 6,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
        TableDef {
            name: "rental",
            foreign_keys: [
                ForeignKeysInfo {
                    id: 0,
                    seq: 0,
                    table: "customer",
                    from: [
                        "customer_id",
                    ],
                    to: [
                        "customer_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 1,
                    seq: 0,
                    table: "inventory",
                    from: [
                        "inventory_id",
                    ],
                    to: [
                        "inventory_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
                ForeignKeysInfo {
                    id: 2,
                    seq: 0,
                    table: "staff",
                    from: [
                        "staff_id",
                    ],
                    to: [
                        "staff_id",
                    ],
                    on_update: NoAction,
                    on_delete: NoAction,
                    match: None,
                },
            ],
            indexes: [],
            constraints: [],
            columns: [
                ColumnInfo {
                    cid: 0,
                    name: "rental_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: true,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 1,
                    name: "rental_date",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 2,
                    name: "inventory_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 3,
                    name: "customer_id",
                    type: BigInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 4,
                    name: "return_date",
                    type: Timestamp,
                    not_null: false,
                    default_value: Null,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 5,
                    name: "staff_id",
                    type: SmallInteger,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
                ColumnInfo {
                    cid: 6,
                    name: "last_update",
                    type: Timestamp,
                    not_null: true,
                    default_value: Unspecified,
                    primary_key: false,
                    hidden: Visible,
                },
            ],
            auto_increment: false,
        },
    ],
    indexes: [
        IndexInfo {
            type: "index",
            index_name: "idx_actor_last_name",
            table_name: "actor",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "last_name",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_country_id",
            table_name: "city",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "country_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_city_id",
            table_name: "address",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "city_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_customer_last_name",
            table_name: "customer",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "last_name",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_customer_fk_address_id",
            table_name: "customer",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "address_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_customer_fk_store_id",
            table_name: "customer",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "store_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_original_language_id",
            table_name: "film",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "original_language_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_language_id",
            table_name: "film",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "language_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_film_actor_actor",
            table_name: "film_actor",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "actor_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_film_actor_film",
            table_name: "film_actor",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "film_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_film_category_category",
            table_name: "film_category",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "category_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_film_category_film",
            table_name: "film_category",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "film_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_film_id_store_id",
            table_name: "inventory",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "store_id",
                "film_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_film_id",
            table_name: "inventory",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "film_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_staff_address_id",
            table_name: "staff",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "address_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_staff_store_id",
            table_name: "staff",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "store_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_store_address",
            table_name: "store",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "address_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_store_fk_manager_staff_id",
            table_name: "store",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "manager_staff_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_customer_id",
            table_name: "payment",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "customer_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_fk_staff_id",
            table_name: "payment",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "staff_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_rental_uq",
            table_name: "rental",
            unique: true,
            origin: "c",
            partial: 0,
            columns: [
                "rental_date",
                "inventory_id",
                "customer_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_rental_fk_staff_id",
            table_name: "rental",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "staff_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_rental_fk_customer_id",
            table_name: "rental",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "customer_id",
            ],
        },
        IndexInfo {
            type: "index",
            index_name: "idx_rental_fk_inventory_id",
            table_name: "rental",
            unique: false,
            origin: "c",
            partial: 0,
            columns: [
                "inventory_id",
            ],
        },
    ],
}"#
    );

    Ok(())
}
