SELECT version()

VersionQueryResult { version: "8.0.23-0ubuntu0.20.04.1" }
Version { number: 80023, system: "0ubuntu0.20.04.1", suffix: [] }

SELECT `column_name`, `column_type`, `is_nullable`, `column_key`, `column_default`, `extra`, `generation_expression`, `column_comment` FROM `information_schema`.`columns` WHERE `table_schema` = ? AND `table_name` = ? ORDER BY `ordinal_position` ASC

ColumnQueryResult { column_name: "film_id", column_type: "smallint unsigned", is_nullable: "NO", column_key: "PRI", column_default: None, extra: "auto_increment", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "film_id", col_type: SmallInt(NumericAttr { maximum: None, decimal: None, unsigned: Some(true), zero_fill: None }), null: false, key: Primary, default: None, extra: ColumnExtra { auto_increment: true, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "title", column_type: "varchar(128)", is_nullable: "NO", column_key: "MUL", column_default: None, extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "title", col_type: Varchar(StringAttr { length: Some(128), charset_name: None, collation_name: None }), null: false, key: Multiple, default: None, extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "description", column_type: "text", is_nullable: "YES", column_key: "", column_default: None, extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "description", col_type: Text(StringAttr { length: None, charset_name: None, collation_name: None }), null: true, key: NotKey, default: None, extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "release_year", column_type: "year", is_nullable: "YES", column_key: "", column_default: None, extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "release_year", col_type: Year, null: true, key: NotKey, default: None, extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "language_id", column_type: "tinyint unsigned", is_nullable: "NO", column_key: "MUL", column_default: None, extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "language_id", col_type: TinyInt(NumericAttr { maximum: None, decimal: None, unsigned: Some(true), zero_fill: None }), null: false, key: Multiple, default: None, extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "original_language_id", column_type: "tinyint unsigned", is_nullable: "YES", column_key: "MUL", column_default: None, extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "original_language_id", col_type: TinyInt(NumericAttr { maximum: None, decimal: None, unsigned: Some(true), zero_fill: None }), null: true, key: Multiple, default: None, extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "rental_duration", column_type: "tinyint unsigned", is_nullable: "NO", column_key: "", column_default: Some("3"), extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "rental_duration", col_type: TinyInt(NumericAttr { maximum: None, decimal: None, unsigned: Some(true), zero_fill: None }), null: false, key: NotKey, default: Some(ColumnDefault { expr: "3" }), extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "rental_rate", column_type: "decimal(4,2)", is_nullable: "NO", column_key: "", column_default: Some("4.99"), extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "rental_rate", col_type: Decimal(NumericAttr { maximum: Some(4), decimal: Some(2), unsigned: None, zero_fill: None }), null: false, key: NotKey, default: Some(ColumnDefault { expr: "4.99" }), extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "length", column_type: "smallint unsigned", is_nullable: "YES", column_key: "", column_default: None, extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "length", col_type: SmallInt(NumericAttr { maximum: None, decimal: None, unsigned: Some(true), zero_fill: None }), null: true, key: NotKey, default: None, extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "replacement_cost", column_type: "decimal(5,2)", is_nullable: "NO", column_key: "", column_default: Some("19.99"), extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "replacement_cost", col_type: Decimal(NumericAttr { maximum: Some(5), decimal: Some(2), unsigned: None, zero_fill: None }), null: false, key: NotKey, default: Some(ColumnDefault { expr: "19.99" }), extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "rating", column_type: "enum(\'G\',\'PG\',\'PG-13\',\'R\',\'NC-17\')", is_nullable: "YES", column_key: "", column_default: Some("G"), extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "rating", col_type: Enum(EnumDef { values: ["G", "PG", "PG-13", "R", "NC-17"], attr: StringAttr { length: None, charset_name: None, collation_name: None } }), null: true, key: NotKey, default: Some(ColumnDefault { expr: "G" }), extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "special_features", column_type: "set(\'Trailers\',\'Commentaries\',\'Deleted Scenes\',\'Behind the Scenes\')", is_nullable: "YES", column_key: "", column_default: None, extra: "", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "special_features", col_type: Set(SetDef { members: ["Trailers", "Commentaries", "Deleted Scenes", "Behind the Scenes"], attr: StringAttr { length: None, charset_name: None, collation_name: None } }), null: true, key: NotKey, default: None, extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: false, generated: false, default_generated: false }, expression: None, comment: "" }
ColumnQueryResult { column_name: "last_update", column_type: "timestamp", is_nullable: "NO", column_key: "", column_default: Some("CURRENT_TIMESTAMP"), extra: "DEFAULT_GENERATED on update CURRENT_TIMESTAMP", generation_expression: Some(""), column_comment: "" }
ColumnInfo { name: "last_update", col_type: Timestamp(TimeAttr { fractional: None }), null: false, key: NotKey, default: Some(ColumnDefault { expr: "CURRENT_TIMESTAMP" }), extra: ColumnExtra { auto_increment: false, on_update_current_timestamp: true, generated: false, default_generated: true }, expression: None, comment: "" }

SELECT `non_unique`, `index_name`, `column_name`, `collation`, `sub_part`, `nullable`, `index_type`, `index_comment`, `expression` FROM `information_schema`.`statistics` WHERE `table_schema` = ? AND `table_name` = ? ORDER BY `index_name` ASC, `seq_in_index` ASC

IndexQueryResult { non_unique: 1, index_name: "idx_fk_language_id", column_name: Some("language_id"), collation: Some("A"), sub_part: None, nullable: "", index_type: "BTREE", index_comment: "", expression: None }
IndexQueryResult { non_unique: 1, index_name: "idx_fk_original_language_id", column_name: Some("original_language_id"), collation: Some("A"), sub_part: None, nullable: "YES", index_type: "BTREE", index_comment: "", expression: None }
IndexQueryResult { non_unique: 1, index_name: "idx_title", column_name: Some("title"), collation: Some("A"), sub_part: None, nullable: "", index_type: "BTREE", index_comment: "", expression: None }
IndexQueryResult { non_unique: 0, index_name: "PRIMARY", column_name: Some("film_id"), collation: Some("A"), sub_part: None, nullable: "", index_type: "BTREE", index_comment: "", expression: None }

IndexInfo { unique: false, name: "idx_fk_language_id", columns: ["language_id"], order: Ascending, sub_part: None, nullable: false, idx_type: BTree, comment: "", functional: false }
IndexInfo { unique: false, name: "idx_fk_original_language_id", columns: ["original_language_id"], order: Ascending, sub_part: None, nullable: true, idx_type: BTree, comment: "", functional: false }
IndexInfo { unique: false, name: "idx_title", columns: ["title"], order: Ascending, sub_part: None, nullable: false, idx_type: BTree, comment: "", functional: false }
IndexInfo { unique: true, name: "PRIMARY", columns: ["film_id"], order: Ascending, sub_part: None, nullable: false, idx_type: BTree, comment: "", functional: false }

SELECT `key_column_usage`.`constraint_name`, `key_column_usage`.`column_name`, `key_column_usage`.`referenced_table_name`, `key_column_usage`.`referenced_column_name`, `referential_constraints`.`update_rule`, `referential_constraints`.`delete_rule` FROM `information_schema`.`key_column_usage` INNER JOIN `information_schema`.`referential_constraints` ON (`key_column_usage`.`constraint_schema` = `referential_constraints`.`constraint_schema`) AND (`key_column_usage`.`constraint_name` = `referential_constraints`.`constraint_name`) WHERE `key_column_usage`.`constraint_schema` = ? AND `key_column_usage`.`table_name` = ? ORDER BY `constraint_name` ASC, `ordinal_position` ASC

ConstraintQueryResult { constraint_name: "fk_film_language", column_name: "language_id", referenced_table_name: "language", referenced_column_name: "language_id", update_rule: "CASCADE", delete_rule: "RESTRICT" }
ConstraintQueryResult { constraint_name: "fk_film_language_original", column_name: "original_language_id", referenced_table_name: "language", referenced_column_name: "language_id", update_rule: "CASCADE", delete_rule: "RESTRICT" }

ForeignKeyInfo { name: "fk_film_language", columns: ["language_id"], referenced_table: "language", referenced_columns: ["language_id"], on_update: Cascade, on_delete: Restrict }
ForeignKeyInfo { name: "fk_film_language_original", columns: ["original_language_id"], referenced_table: "language", referenced_columns: ["language_id"], on_update: Cascade, on_delete: Restrict }

